version: '3'
services:
  python3:
    build: .
    container_name: 'discord'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    extra_hosts:                 
        - localhost:172.18.0.1  